import { useEffect, useState } from "react";
import ModelUsagePie from "../charts/ModelUsagePie";

const API = "http://127.0.0.1:8000";

function fmt(n) {
  if (!n || n === 0) return "0";
  if (n < 0.000001) return (n * 1e9).toFixed(2) + " ng";
  if (n < 0.001)    return (n * 1e6).toFixed(2) + " µg";
  if (n < 1)        return (n * 1000).toFixed(4) + " mg";
  return n.toFixed(4) + " kg";
}

export default function AdminDashboard() {
  const [analytics, setAnalytics] = useState(null);
  const [loading, setLoading]     = useState(true);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    fetch(`${API}/analytics`)
      .then(r => r.json())
      .then(data => { setAnalytics(data); setLoading(false); })
      .catch(() => setLoading(false));
  }, []);

  // const exportCSV = async () => {
  //   if (!analytics) return;
  //   setExporting(true);

  //   const rows = [
  //     ["Metric", "Value"],
  //     ["Total Requests",   analytics.total_requests],
  //     ["Cache Hits",       analytics.cache_hits],
  //     ["Cache Hit Rate",   analytics.cache_hit_rate + "%"],
  //     ["CO2 Used (kg)",    analytics.total_co2_kg],
  //     ["CO2 Saved (kg)",   analytics.total_saved_kg],
  //     ["CO2 Baseline (kg)", analytics.total_baseline_kg],
  //     [],
  //     ["Tier", "Requests"],
  //     ...Object.entries(analytics.tier_distribution),
  //     [],
  //     ["Day", "CO2 Used", "CO2 Saved", "Requests", "Cache Hits"],
  //     ...analytics.daily_trend.map(d =>
  //       [d.day, d.co2_used, d.co2_saved, d.requests, d.cache_hits]
  //     ),
  //   ];

  //   const csv = rows.map(r => r.join(",")).join("\n");
  //   const blob = new Blob([csv], { type: "text/csv" });
  //   const url  = URL.createObjectURL(blob);
  //   const a    = document.createElement("a");
  //   a.href     = url;
  //   a.download = `carbonsight-esg-${new Date().toISOString().slice(0,10)}.csv`;
  //   a.click();
  //   URL.revokeObjectURL(url);
  //   setExporting(false);
  // };

  const exportESG = () => {
    if (!analytics) return;
    setExporting(true);

    const date = new Date().toISOString().slice(0, 10);
    const year = new Date().getFullYear();

    // --- Summary section ---
    const avoidancePct = analytics.total_baseline_kg > 0
      ? Math.min(
          ((analytics.total_saved_kg / (analytics.total_baseline_kg + analytics.total_co2_kg)) * 100),
          100
        ).toFixed(1)
      : 0;

    const rows = [
      // Cover
      ["CARBONSIGHT ESG CARBON REPORT"],
      [`Report Date: ${date}`],
      [`Reporting Period: ${analytics.daily_trend[0]?.day ?? "—"} to ${analytics.daily_trend.at(-1)?.day ?? "—"}`],
      [`Generated by: CarbonSight v2`],
      [],

      // Methodology
      ["METHODOLOGY"],
      ["Scope", "GHG Protocol Scope 2 proxy (purchased compute energy)"],
      ["Emission factor", "0.475 gCO₂ per Wh (default)"],
      ["Baseline", "All-Pro counterfactual — cost if every request used the heaviest model with no caching"],
      ["Avoided emissions", "Baseline CO₂ minus actual CO₂ across all requests"],
      ["Verification", "Hash-linked local attestation chain (see /attestation/verify)"],
      [],

      // Executive summary
      ["EXECUTIVE SUMMARY"],
      ["Metric", "Value", "Unit"],
      ["Total AI Requests",        analytics.total_requests,                   "requests"],
      ["Cache Hit Rate",           analytics.cache_hit_rate,                   "%"],
      ["Actual CO₂ Emitted",       analytics.total_co2_kg.toExponential(4),    "kg CO₂e"],
      ["CO₂ Avoided",              analytics.total_saved_kg.toExponential(4),  "kg CO₂e"],
      ["Pro-Baseline CO₂",         analytics.total_baseline_kg.toExponential(4), "kg CO₂e"],
      ["Avoidance Rate vs Baseline", avoidancePct,                             "%"],
      [],

      // Tier breakdown
      ["MODEL TIER DISTRIBUTION"],
      ["Tier", "Requests", "% of Total", "Carbon Intensity"],
      ...Object.entries(analytics.tier_distribution).map(([tier, count]) => [
        tier,
        count,
        analytics.total_requests > 0
          ? ((count / analytics.total_requests) * 100).toFixed(1) + "%"
          : "0%",
        tier === "cache" ? "0 (avoided)"
          : tier === "micro" ? "Lowest"
          : tier === "lite"  ? "Medium"
          : "Highest",
      ]),
      [],

      // Daily log
      ["DAILY ACTIVITY LOG"],
      ["Date", "Requests", "Cache Hits", "Cache Hit Rate", "CO₂ Used (kg)", "CO₂ Saved (kg)"],
      ...analytics.daily_trend.map(d => [
        d.day,
        d.requests,
        d.cache_hits,
        d.requests > 0 ? ((d.cache_hits / d.requests) * 100).toFixed(1) + "%" : "0%",
        d.co2_used.toExponential(4),
        d.co2_saved.toExponential(4),
      ]),
      [],

      // Attestation note
      ["ATTESTATION"],
      ["All routing events are recorded in a hash-linked attestation chain."],
      ["Verify integrity at: GET /attestation/verify"],
      ["Each block contains: org_id, user_id, prompt_hash, tier, co2_kg, co2_saved_kg, baseline_co2_kg"],
      ["Blocks are SHA-256 chained — any modification invalidates all subsequent records."],
      [],

      // Disclosure
      ["DISCLOSURE"],
      ["This report uses estimated energy coefficients based on published model benchmarks."],
      ["Figures represent Scope 2 proxy emissions from AI inference only."],
      ["Training emissions (Scope 3.1) are not included in this report."],
      [`Report generated: ${new Date().toISOString()}`],
    ];

    const csv = rows.map(r =>
      r.map(cell => {
        const s = String(cell ?? "");
        return s.includes(",") || s.includes("\n") ? `"${s}"` : s;
      }).join(",")
    ).join("\n");

    const blob = new Blob([csv], { type: "text/csv" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = `carbonsight-esg-${date}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    setExporting(false);
  };

  if (loading) return (
    <div className="h-screen bg-[#0E0F10] flex items-center justify-center text-white/40">
      Loading…
    </div>
  );

  const tierData = analytics
    ? Object.fromEntries(
        Object.entries(analytics.tier_distribution).map(([k, v]) => [
          k === "cache" ? "Cache Hit" : k.charAt(0).toUpperCase() + k.slice(1), v
        ])
      )
    : {};

  const avoidanceRate = analytics?.total_baseline_kg > 0
    ? Math.min(
        ((analytics.total_saved_kg / (analytics.total_baseline_kg + analytics.total_co2_kg)) * 100),
        100
      ).toFixed(1)
    : 0;

  return (
    <div className="min-h-screen bg-[#0E0F10] p-8 text-white space-y-8">

      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-semibold">Admin Dashboard</h1>
        <a href="/" className="text-sm text-white/40 hover:text-white transition">← Back to chat</a>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="bg-[#1A1C1E] p-5 rounded-xl">
          <p className="text-xs text-white/50 mb-1">Total Requests</p>
          <p className="text-2xl font-bold">{analytics?.total_requests ?? "—"}</p>
        </div>
        <div className="bg-[#1A1C1E] p-5 rounded-xl">
          <p className="text-xs text-white/50 mb-1">Cache Hit Rate</p>
          <p className="text-2xl font-bold text-green-400">{analytics?.cache_hit_rate ?? 0}%</p>
        </div>
        <div className="bg-[#1A1C1E] p-5 rounded-xl">
          <p className="text-xs text-white/50 mb-1">CO₂ Avoided</p>
          <p className="text-2xl font-bold text-green-400">{fmt(analytics?.total_saved_kg)}</p>
        </div>
        <div className="bg-[#1A1C1E] p-5 rounded-xl">
          <p className="text-xs text-white/50 mb-1">Avoidance Rate</p>
          <p className="text-2xl font-bold text-blue-400">{avoidanceRate}%</p>
          <p className="text-xs text-white/30 mt-1">vs Pro baseline</p>
        </div>
      </div>

      {/* ESG figures */}
      <div className="bg-[#1A1C1E] p-6 rounded-xl border border-green-400/20">
        <h2 className="text-xl font-semibold mb-1">ESG Carbon Summary</h2>
        <p className="text-white/40 text-xs mb-5">
          Scope 2 proxy — purchased compute energy × emission factor (0.475 gCO₂/Wh)
        </p>
        <div className="grid grid-cols-3 gap-6">
          <div>
            <p className="text-xs text-white/50 mb-1">Baseline (all-Pro counterfactual)</p>
            <p className="text-xl font-semibold text-white/70">{fmt(analytics?.total_baseline_kg)}</p>
          </div>
          <div>
            <p className="text-xs text-white/50 mb-1">Actual CO₂ used</p>
            <p className="text-xl font-semibold text-orange-400">{fmt(analytics?.total_co2_kg)}</p>
          </div>
          <div>
            <p className="text-xs text-white/50 mb-1">Avoided emissions</p>
            <p className="text-xl font-semibold text-green-400">{fmt(analytics?.total_saved_kg)}</p>
          </div>
        </div>
      </div>

      {/* Tier pie + breakdown table side by side */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-white/5 p-6 rounded-xl">
          <h2 className="text-xl mb-4">Model Tier Distribution</h2>
          <ModelUsagePie data={tierData} />
        </div>

        <div className="bg-[#1A1C1E] p-6 rounded-xl">
          <h2 className="text-xl mb-4">Tier Breakdown</h2>
          <table className="w-full text-left text-sm text-white/80">
            <thead>
              <tr className="text-white/40 text-xs uppercase tracking-wide">
                <th className="pb-3">Tier</th>
                <th className="pb-3">Requests</th>
                <th className="pb-3">Share</th>
              </tr>
            </thead>
            <tbody>
              {Object.entries(analytics?.tier_distribution ?? {}).map(([tier, count]) => (
                <tr key={tier} className="border-t border-white/5">
                  <td className="py-2 capitalize">{tier}</td>
                  <td className="py-2">{count}</td>
                  <td className="py-2 text-white/50">
                    {analytics.total_requests > 0
                      ? ((count / analytics.total_requests) * 100).toFixed(1)
                      : 0}%
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Daily trend table */}
      <div className="bg-[#1A1C1E] p-6 rounded-xl">
        <h2 className="text-xl font-semibold mb-4">Daily Activity Log</h2>
        <table className="w-full text-left text-sm text-white/80">
          <thead>
            <tr className="text-white/40 text-xs uppercase tracking-wide">
              <th className="pb-3">Date</th>
              <th className="pb-3">Requests</th>
              <th className="pb-3">Cache Hits</th>
              <th className="pb-3">CO₂ Used</th>
              <th className="pb-3">CO₂ Saved</th>
            </tr>
          </thead>
          <tbody>
            {(analytics?.daily_trend ?? []).map((row, i) => (
              <tr key={i} className="border-t border-white/5">
                <td className="py-2">{row.day}</td>
                <td className="py-2">{row.requests}</td>
                <td className="py-2 text-green-400">{row.cache_hits}</td>
                <td className="py-2 text-orange-400">{fmt(row.co2_used)}</td>
                <td className="py-2 text-green-400">{fmt(row.co2_saved)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* ESG Export */}
      <div className="flex gap-4">
        <button
          onClick={exportESG}
          disabled={exporting}
          className="bg-green-500 px-6 py-3 rounded-lg text-black font-semibold hover:bg-green-400 disabled:opacity-50 transition"
        >
          {exporting ? "Exporting…" : "Export ESG Report (CSV)"}
        </button>
        <span className="text-xs text-white/30 self-center">
          PDF export available after org auth layer is added
        </span>
      </div>

    </div>
  );
}